train:
  _target_: src.datasets.CustomDirDataset
  audio_dir: "dla_dataset/audio/train"
  instance_transforms: ${transforms.instance_transforms.train}
  type: ${trainer.dataset_type}
val:
  _target_: src.datasets.CustomDirDataset
  audio_dir: "dla_dataset/audio/val"
  instance_transforms: ${transforms.instance_transforms.inference}
  type: ${trainer.dataset_type}

