train:
  _target_: src.datasets.CustomDirDataset
  audio_dir: "dla_dataset/audio/train"
  limit: 2
  instance_transforms: ${transforms.instance_transforms.train}
  type: ${trainer.dataset_type}
# we filter partitions in one batch test to check the pipeline
# do not filter test dataset, you want to evaluate on the whole dataset
val:
  _target_: src.datasets.CustomDirDataset
  audio_dir: "dla_dataset/audio/val"
  limit: 2
  instance_transforms: ${transforms.instance_transforms.inference}
  type: ${trainer.dataset_type}
