train: [] # metrics that are calculated during training
  # - _target_: src.metrics.SISDRMetric
  #   name: "SI-SDR" # it is better to avoid spaces in names
inference: # metrics that are calculated during inference (eval)
  - _target_: src.metrics.SISDRMetric
    name: "SI-SDR" # it is better to avoid spaces in names

