defaults:
  - model: tdavss
  - writer: wandb
  - metrics: train_and_val
  - datasets: example
  - dataloader: example
  - transforms: tdavss
  - _self_
optimizer:
  _target_: torch.optim.AdamW
  lr: 1e-3
lr_scheduler:
  _target_: torch.optim.lr_scheduler.OneCycleLR
  max_lr: 1e-2
  pct_start: 0.2
  steps_per_epoch: ${trainer.epoch_len}
  epochs: ${trainer.n_epochs}
  anneal_strategy: cos
loss_function:
  _target_: src.loss.SISNR
  need_pit: False
trainer:
  log_step: 50
  n_epochs: 70
  epoch_len: 2000
  device_tensors: ["mix", "target", "mouth"] # which tensors should be on device (ex. GPU)
  resume_from: null # null or path to the checkpoint dir with *.pth and config.yaml
  device: auto # device name or "auto"
  override: True # if True, will override the previous run with the same name
  monitor: "max val_SI-SNRi" # "off" or "max/min metric_name", i.e. our goal is to maximize/minimize metric
  save_period: 5 # checkpoint each save_period epochs in addition to the best epoch
  early_stop: ${trainer.n_epochs} # epochs for early stopping
  save_dir: "saved"
  seed: 1
  sample_rate: 16000
  dataset_type: "single_target"
  video_model_pretrained: "data/pretrained_video_model/lrw_resnet18_dctcn_video.pth"